Create CRUD models and Repositories.
iryna-pantsialeyeva/boarderpicker pull request #3
Opened 2022-12-25 15:47 UTC by ilya-frolov

Check our Models and Repositories, please.

2022-12-26 13:29 UTC, RomanKashenok requested changes
Есть над чем часок посидеть
вот тут посмотри про ManyToMany:
https://www.baeldung.com/hibernate-many-to-many

2022-12-26 13:29 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/User.java
> +            inverseJoinColumns = {@JoinColumn(name = "games_id")})
@ManyToMany(mappedBy = "users")

2022-12-26 13:29 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Role.java
> +            inverseJoinColumns = {@JoinColumn(name = "users_id")})
@manytomany(mappedBy = "roles")

2022-12-26 13:29 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Role.java
> +            inverseJoinColumns = {@JoinColumn(name = "users_id")})
замени на это и будет хорошо

2022-12-26 13:29 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Category.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
Кажись вы хотели сделать что бы одна игра была в разных категориях, не?

2022-12-26 13:29 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    @Column(name = "GAMENAME")
давай всё с маленькой буквы

2022-12-26 22:36 UTC, ilya-frolov commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    @Column(name = "GAMENAME")
Сделано

2022-12-26 22:37 UTC, ilya-frolov commented on src/main/java/info/freeit/boarderpicker/entity/Category.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
Исправил тип зависимости

2022-12-26 22:37 UTC, ilya-frolov commented on src/main/java/info/freeit/boarderpicker/entity/Role.java
> +            inverseJoinColumns = {@JoinColumn(name = "users_id")})
Почитал, понял, изменил.

2022-12-26 22:37 UTC, ilya-frolov commented on src/main/java/info/freeit/boarderpicker/entity/User.java
> +            inverseJoinColumns = {@JoinColumn(name = "games_id")})
Совсем изменил эту зависимость, т. к. в таблице "sales" нам необходимо дополнительное поле.

2022-12-27 07:45 UTC, RomanKashenok approved these changes

2022-12-27 20:09 UTC, merged