Create REST Controllers for Users-Roles CRUD operations + Implement add service logic for base entities (User)
iryna-pantsialeyeva/boarderpicker pull request #4
Opened 2022-12-29 12:54 UTC by iryna-pantsialeyeva

Please review my PR

2022-12-30 20:09 UTC, RomanKashenok requested changes

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    @OnDelete(action = OnDeleteAction.NO_ACTION)
не обязательно вообще (я б убрал)

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    }
не надо так делать. Убери это пожалуйста

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/User.java
> +    }
вот это - плохо так делать, если уж хибернейт используем

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/entity/Sale.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
лишнее

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/exception/ObjectAlreadyExistException.java
> +public class ObjectAlreadyExistException extends Exception {
я бы убрал и юзал стандартный IllegalArgumentException

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends Exception {
замени это все на какой-то более general эксепшн. типа GamesPersistanceException или чет такое

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +        List<User> users = Streamable.of(userRepository.findAll()).toList();
а тебе точно нужна поточная обработка? Давай просто сразу список из репозитория достанем, а?

2022-12-30 20:09 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +            userRepository.deleteById(id);
ты можешь сразу удалять по айди не делая два запроса в базу

2023-01-02 17:23 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/entity/Sale.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
При удалении игры мы хотим, чтобы удалялась sale, без аннотацию падает с ошибкой, т.к. есть связанная запись в сейле.

2023-01-02 18:19 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +            userRepository.deleteById(id);
Можно сразу удалять.  Но из описания метода deleteById() : Если энтити с таким id не будет найден, это будет проигнорировано "silently". Я хотела, чтобы клиент видел, что он ввел несуществующий id (реализовано с помощью выброса кастомного эксепшена).

2023-01-02 18:38 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/entity/User.java
> +    }
Согласна, что можно без них. Достаточно геттера для получения получения хэшсетов и вызова на них метода add().

2023-01-02 18:39 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    }
Согласна, что можно без addSale(). Достаточно геттера для получения получения хэшсета и вызова на них метода add().

2023-01-02 18:53 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/exception/ObjectAlreadyExistException.java
> +public class ObjectAlreadyExistException extends Exception {
Сделано.

2023-01-02 18:55 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/exception/ObjectNotFoundException.java
> +public class ObjectNotFoundException extends Exception {
ObjectNotFoundException заменено на ObjectPersistanceException

2023-01-02 19:31 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +        List<User> users = Streamable.of(userRepository.findAll()).toList();
Точно нужна. Я хочу вернуть List, а на коллекции типа Iterable нельзя вызвать stream чтобы преобразовать в List объектов dto.

2023-01-02 19:37 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/entity/Game.java
> +    @OnDelete(action = OnDeleteAction.NO_ACTION)
Сделано

2023-01-04 14:46 UTC, RomanKashenok approved these changes

2023-01-04 14:46 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/exception/ObjectPersistenceException.java
> +public class ObjectPersistenceException extends Exception {
Давай в следующих коммитах сделаем его рантайм и уберем его пробрасывания в коде

2023-01-04 14:46 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +    public void deleteUser(@RequestParam int id) throws ObjectPersistenceException {
Убери это как сделаешь исключение рантайм

2023-01-04 14:46 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +    public UserDTO getUserByID(int userID) throws ObjectPersistenceException {
убери как сделаешь рантайм

2023-01-04 14:46 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/service/UserService.java
> +    UserDTO getUserByID(int userID) throws ObjectPersistenceException;
убери как сделаешь рантайм

2023-01-04 15:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +    @PostMapping("/save")
убери слова эти /save, /delete, /update - это и так из методов понятно

2023-01-04 15:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +        List<User> users = Streamable.of(userRepository.findAll()).toList();
тогда давай так:
return Streamable.of(userRepository.findAll()).stream().map(user -> UserDTO.fromUser(user)).toList();

2023-01-04 19:52 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +        List<User> users = Streamable.of(userRepository.findAll()).toList();
Сделано

2023-01-04 20:11 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +    @PostMapping("/save")
сделано

2023-01-04 20:11 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/UserService.java
> +    UserDTO getUserByID(int userID) throws ObjectPersistenceException;
сделано

2023-01-04 20:12 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +    public UserDTO getUserByID(int userID) throws ObjectPersistenceException {
сделано

2023-01-04 20:13 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +    public void deleteUser(@RequestParam int id) throws ObjectPersistenceException {
Сделано

2023-01-04 20:14 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/exception/ObjectPersistenceException.java
> +public class ObjectPersistenceException extends Exception {
Убрала вместе с папкой exception

2023-01-04 20:15 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/service/Impl/UserServiceImpl.java
> +        List<User> users = Streamable.of(userRepository.findAll()).toList();
сделано

2023-01-04 20:28 UTC, merged