Dev spring security
iryna-pantsialeyeva/boarderpicker pull request #7
Opened 2023-01-08 20:24 UTC by iryna-pantsialeyeva

Please review my PR
BPR-8 Add web security with "path" security

2023-01-12 10:16 UTC, RomanKashenok requested changes
Минимально поправь пожалуйста, а так - всё хорошо! :)

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/config/SecurityConfig.java
> +                .headers().frameOptions().sameOrigin()
👏 👏 👏 
молодец!

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/AdminController.java
> +@PreAuthorize("hasAuthority('Admin')")
если закрывать весь контроллер, то, наверное, лучше в конфиге безопасности

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +@PreAuthorize("hasAnyAuthority('User', 'Admin')")
убери наверное отсюда

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
>      @GetMapping("/")
Вот тут можно закрыть эндпойнт только для админов (зачем юзеру знать всех остальных юзеров)?

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +        return userService.updateUser(userID, userDTO);
Тут посоветую, раз уже безопасность прикручена, достать текущего юзера из контекста и сравнить айдишники - вдруг юзер хочет поменять инфу другого юзера? ))

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/dto/UserDTO.java
> +public class UserDTO implements UserDetails {
Не, UserDto - это то, что ты предоставляешь наружу. В нем не должно быть ни пароля, ли ролей. Поэтому для идентификации заведи просто отдельный класс типа BPUserDetails и храни там то, что тебе необходимо )

2023-01-12 10:16 UTC, RomanKashenok commented on src/main/java/info/freeit/boarderpicker/dto/UserDTOForSaveUpdate.java
> +public class UserDTOForSaveUpdate {
UpdateUserDto? - update - это же тот же save  по идее )) и наоборот ))

2023-01-12 19:46 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/AdminController.java
> +@PreAuthorize("hasAuthority('Admin')")
сделано

2023-01-12 19:47 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +@PreAuthorize("hasAnyAuthority('User', 'Admin')")
после добавления матчера админа в конфиг работает без этой аннотации. убрала

2023-01-12 19:51 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
>      @GetMapping("/")
Согласна. сделала.

2023-01-13 18:39 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/controller/UserController.java
> +        return userService.updateUser(userID, userDTO);
Сделано. Спасибо за идею

2023-01-13 18:40 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/dto/UserDTO.java
> +public class UserDTO implements UserDetails {
Сделано

2023-01-13 18:40 UTC, iryna-pantsialeyeva commented on src/main/java/info/freeit/boarderpicker/dto/UserDTOForSaveUpdate.java
> +public class UserDTOForSaveUpdate {
Изменила название

2023-01-16 14:44 UTC, RomanKashenok approved these changes

2023-01-17 15:11 UTC, merged